title: PRESTIGIO
description: largarta
template:
  repo: PRESTIGIO
  name: PRESTIGIO
  description: largarta
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: assignRegistrant
steps:
  - title: busca
    description: largarta
    event: issues.assigned
    link: fotos
    actions:
      - type: closeIssue
      - type: createPullRequest
    video: golgle
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
