title: PRESTIGIO
description: >-
  Em caso de pane do veículo acionando o SOS no celular ativar sistema de
  atendimento e enviar socorro para o local que o veículo se encontra o qual já
  estará integrado ao sistema GPS. e os dados do veículo e condutor já estará
  inserido no sistema.
template:
  repo: prestigio-template
  name: prestigio
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
